# Site settings
title: William Thulin
description: Personligt CV
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: William Thulin
user_description: Social, omtänksam, utåtriktad och stresstålig, van att tala inför grupp! Erfaren inom vård med individens behov i fokus
user_title: Psykolog
email: test@gmail.com
# twitter_username: lorem_ipsum
instagram_username: mauriciourraco7
facebook_username: mauricio.urraco
linkedin_username: murraco
github_username:  murraco
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']
